// generated by stringer -type=Level; DO NOT EDIT

package log

import "fmt"

const _Level_name = "DisableLogLevelFatalLevelErrorLevelInfoLevelDebugLevel"

var _Level_index = [...]uint8{0, 15, 25, 35, 44, 54}

func (i Level) String() string {
	if i >= Level(len(_Level_index)-1) {
		return fmt.Sprintf("Level(%d)", i)
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
